#!/bin/bash

IN_SCREEN=
# [ "$TERM" = "screen" ] is not a sufficient indicator
# since we override it in ~/.screen.d/colours
if [ -n "$STY" ] || [ "$TERM" = "screen" ]; then
    IN_SCREEN=yes
fi
export IN_SCREEN

export SCREENRC=$ZDOTDIR/.screenrc
