#!/bin/bash

# Fix issues with screen's terminfo description which lacks
# italics and confuses it with standout mode.
#
# (from http://tmux.svn.sourceforge.net/viewvc/tmux/trunk/FAQ)
for screen_terminfo in screen-256color{,-bce}; do
    if ! infocmp "$screen_terminfo" >/dev/null 2>&1; then
        echo "$screen_terminfo not defined; skipping ..."
        continue
    fi

    infocmp "$screen_terminfo" | \
        sed -e "s/^screen[^|]*|[^,]*,/${screen_terminfo}-it|GNU Screen with 256 colors and italics support,/" \
            -e 's/%?%p1%t;3%/%?%p1%t;7%/' \
            -e 's/smso=[^,]*,/smso=\\E[7m,/' \
            -e 's/rmso=[^,]*,/rmso=\\E[27m,/' \
            -e '$s/$/ sitm=\\E[3m, ritm=\\E[23m,/' \
        > /tmp/screen.terminfo
    [ -d .terminfo ] || mkdir .terminfo
    TERMINFO=`pwd`/.terminfo tic /tmp/screen.terminfo
done

# Check the results with: infocmp screen-256color-bce{,-it}
# N.B. fixups run after stowing, so this will need to be restowed
# manually to take effect :-/
